### ISSUE TITLE
feat: review add jam

### ISSUE THREAD

**Issue by srizvi** [sambi-dev/sambi#144]
https://jam.dev

**Comment by srizvi** [comment]
Installed, pretty sweet. @ambi-dar & @rradice13 would be cool for you to have too. (optional)

**Comment by rradice13** [comment]
Jam is really cool! Watched her quick video - can see how grabbing the last 30 seconds would be helpful, just not sure the usecase for me and Ambreen outside of our own stuff?

**Comment by srizvi** [comment]
Our stuff.

**Comment by rradice13** [comment]
I used it today for Ronnie. Found a bug.
