### ISSUE TITLE
feat: create accessibility statement

### ISSUE THREAD

**Issue by srizvi** [sambi-dev/sambi#19]

**Comment by ambi-dar** [comment]
@srizvi Creating a word doc similar to the one that's present for Hey Rebekah's website. Just confirming that we are following WCAG 2.1 AA standards.

Also, have you confirmed an email address for inquires etc?
accessibility@sambi.dev
hi@sambi.dev?

**Comment by ambi-dar** [comment]
[Accessibility Statement](https://docs.google.com/document/d/1p95KOB5rqU3B4OeKdLT6iJ92IKdJ6WWrdEmCgBX-PMw/edit)

I'll make edits to the email address and standards, if different.

**Comment by ambi-dar** [comment]
Waiting for feedback here

**Comment by srizvi** [comment]
Updated this to a more casual tone. Published. @ambi-dar you can edit on basehub as needed.
