### ISSUE TITLE
feat: update client svgs

### ISSUE THREAD

**Issue by srizvi** [sambi-dev/sambi#55]
Refer to our and each of our individual client lists too, I drafted one and dropped it into chat last week.

- the edge to edge-to-edge height of the logos (not the svg) needs to be consistent height 96px
- each page name in the file needs to be named `client-logo` or `client-partner-logo` if viaPartner

- [x] #73
- [x] #74

**Comment by ambi-dar** [comment]
Create 100x100 icons for each
